### ISSUE TITLE
Hotspot handling

### ISSUE THREAD

**Issue by piotrlg9** [gravity9-tech/mongo-cse#18]
Describe in documentation or design & implement strategy for handling hotspots in partitioning keys.

What is hotspot?
--------------------
Imagine there is a collection with 1000 documents.

One of them ("ht" - hot document) is modified very frequently:
*  ht: 1000 updates per minute (so 1,440,000 events per day)
* other documents: 1 update per day on average (so 1000 events per day)

Number of events for "ht" document is so large that handling of events will concentrate on "ht" and handling of other documents will be delayed. In the default partitioning approach (1 partition 1 listener) between every non-ht event there will be handling of 1440 ht events.

**Comment by BartekGravity** [comment]
@piotrlg9 this is already possible in this library through configuration. The current default key for partitioning is `_id` but you can use any other field to create partitions. That means you can, for example, divide events into partitions by an `updateDate` field - which would mean the updates, even for the same document, would spread between partitions. 

However, you do have to remember that this is a double-edged sword. If you allow updates for the same document to hit different partitions you might lose ordering and would need to make sure you are handling the order in a custom way (for example by comparing timestamps in the events). It is up to the user to make sure the setup does exactly what is needed by the use case.
